<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
        <title>关注拍拍客</title>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
            .opt {
                text-align: left;
                margin: 1em 1em 1em 1em;
            }
        </style>
    </head>
    <body>
        <h3>拍拍客</h3>
        <div><img src='/images/qrcode_for_gh_15b711976a8a_258.jpg' width='130px' height='130px'/></div>
        <div class="opt">
            <div>操作方法</div>
            <ul>
                <li>1、关注公众号</li>
                <li>2、上传照片</li>
                <li>3、输入"我的"或者"mine"，看自己的照片墙</li>
            </ul>
        </div>
    </body>
</html>
